# -*- coding: utf-8 -*-
"""secret_number

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pBX0-teiUb2kkOio9IvXQf29pKUK96x9
"""

# Introduction :)

print("Welcome to the Secret Number Game!")
print("INSTRUCTIONS!")
print("The program will generate a random secret number between 1 and 100.")
print("Your task is to guess the secret number.")
print("You will have only 8 attempts to guess the secret number.")
print("Good luck!")

# Generating a number between 1 and 100
import random
secretNumber = random.randint(1, 100)

# Counting attempts
attempts = 8

# Loop
for attempt in range(1, attempts + 1):
    guess = int(input(f"Attempt {attempt}: Enter your guess --> "))

    if guess == secretNumber:
        print("Congratulations! You guessed it!")
        print("Thanks for playing!")
        print("Goodbye!")
        break
    elif guess < secretNumber:
        print("Try a higher number.")
    else:
        print("Try a lower number.")

# If the player doesn't guess after all attempts
if guess != secretNumber:
    print("You lost! The secret number was", secretNumber)
    print("Thanks for playing!")
    print("Goodbye!")

# End! :>
# Made by Igor Riba.